baseURL = "http://leitemods.no"
title = "Leitemods"
copyright = "Copyright © 2020 Lars Erik Storbukås"
paginate = 2
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-XXXX"
DisqusShortname = ""
theme = "chunky-poster"
[menu]
   [[menu.main]]
      identifier = "hjem"
      name = "Hjem"
      url = "#"
      weight = 10
[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"
[params]
author = "Lars Erik Storbukås"
description = "Modding av klokker"
homepageImage = "/images/homepage-image.jpg"
share = true
showLanguageSwitcher = false
# Custom CSS and JS. Relative to /static/css and /static/js respectively.
customCSS = []
customJS = []
[params.social]
email = "leitemods@gmail.com"
facebook = "https://facebook.com"
twitter = "https://twitter.com"
instagram = "https://stackoverflow.com"
[params.prismJS]
   enable = true
   theme = ""
[params.commento]
   enable = true
   url = "https://commento.io"
[markup]
   [markup.highlight]
      codeFences = false
[services]
   [services.instagram]
      disableInlineCSS = true
   [services.twitter]
      disableInlineCSS = true
